require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcademiaTreinamentosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AcademiaTreinamento. As you add validations to AcademiaTreinamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcademiaTreinamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all academia_treinamentos as @academia_treinamentos" do
      academia_treinamento = AcademiaTreinamento.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:academia_treinamentos)).to eq([academia_treinamento])
    end
  end

  describe "GET #show" do
    it "assigns the requested academia_treinamento as @academia_treinamento" do
      academia_treinamento = AcademiaTreinamento.create! valid_attributes
      get :show, {:id => academia_treinamento.to_param}, valid_session
      expect(assigns(:academia_treinamento)).to eq(academia_treinamento)
    end
  end

  describe "GET #new" do
    it "assigns a new academia_treinamento as @academia_treinamento" do
      get :new, {}, valid_session
      expect(assigns(:academia_treinamento)).to be_a_new(AcademiaTreinamento)
    end
  end

  describe "GET #edit" do
    it "assigns the requested academia_treinamento as @academia_treinamento" do
      academia_treinamento = AcademiaTreinamento.create! valid_attributes
      get :edit, {:id => academia_treinamento.to_param}, valid_session
      expect(assigns(:academia_treinamento)).to eq(academia_treinamento)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AcademiaTreinamento" do
        expect {
          post :create, {:academia_treinamento => valid_attributes}, valid_session
        }.to change(AcademiaTreinamento, :count).by(1)
      end

      it "assigns a newly created academia_treinamento as @academia_treinamento" do
        post :create, {:academia_treinamento => valid_attributes}, valid_session
        expect(assigns(:academia_treinamento)).to be_a(AcademiaTreinamento)
        expect(assigns(:academia_treinamento)).to be_persisted
      end

      it "redirects to the created academia_treinamento" do
        post :create, {:academia_treinamento => valid_attributes}, valid_session
        expect(response).to redirect_to(AcademiaTreinamento.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved academia_treinamento as @academia_treinamento" do
        post :create, {:academia_treinamento => invalid_attributes}, valid_session
        expect(assigns(:academia_treinamento)).to be_a_new(AcademiaTreinamento)
      end

      it "re-renders the 'new' template" do
        post :create, {:academia_treinamento => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested academia_treinamento" do
        academia_treinamento = AcademiaTreinamento.create! valid_attributes
        put :update, {:id => academia_treinamento.to_param, :academia_treinamento => new_attributes}, valid_session
        academia_treinamento.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested academia_treinamento as @academia_treinamento" do
        academia_treinamento = AcademiaTreinamento.create! valid_attributes
        put :update, {:id => academia_treinamento.to_param, :academia_treinamento => valid_attributes}, valid_session
        expect(assigns(:academia_treinamento)).to eq(academia_treinamento)
      end

      it "redirects to the academia_treinamento" do
        academia_treinamento = AcademiaTreinamento.create! valid_attributes
        put :update, {:id => academia_treinamento.to_param, :academia_treinamento => valid_attributes}, valid_session
        expect(response).to redirect_to(academia_treinamento)
      end
    end

    context "with invalid params" do
      it "assigns the academia_treinamento as @academia_treinamento" do
        academia_treinamento = AcademiaTreinamento.create! valid_attributes
        put :update, {:id => academia_treinamento.to_param, :academia_treinamento => invalid_attributes}, valid_session
        expect(assigns(:academia_treinamento)).to eq(academia_treinamento)
      end

      it "re-renders the 'edit' template" do
        academia_treinamento = AcademiaTreinamento.create! valid_attributes
        put :update, {:id => academia_treinamento.to_param, :academia_treinamento => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested academia_treinamento" do
      academia_treinamento = AcademiaTreinamento.create! valid_attributes
      expect {
        delete :destroy, {:id => academia_treinamento.to_param}, valid_session
      }.to change(AcademiaTreinamento, :count).by(-1)
    end

    it "redirects to the academia_treinamentos list" do
      academia_treinamento = AcademiaTreinamento.create! valid_attributes
      delete :destroy, {:id => academia_treinamento.to_param}, valid_session
      expect(response).to redirect_to(academia_treinamentos_url)
    end
  end

end
